version: 2
updates:
  - package-ecosystem: npm
    directory: "/eslint-config-base"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/eslint-config-lib"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/eslint-config-react"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/eslint-config-react-ts"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  